apiVersion: v1
kind: Service
metadata:
  name: bernardoras-playlists-recommender-system-service
spec:
  selector:
    app: bernardoras-playlists-recommender-system
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 50003