apiVersion: batch/v1
kind: Job
metadata:
  name: playlists-train-bernardoras-ds2 # use dataset version in name
  namespace: bernardosilva
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: give-permission-for-pv
        image: busybox:1.36
        command: ["sh", "-c", "chmod -R 777 /project2"]
        volumeMounts:
        - name: project2-pv2-bernardosilva-volume
          mountPath: /project2
      containers:
      - name: playlists-train
        image: docker.io/bernardoras/playlists-recommender-system-model-generator:0.1
        imagePullPolicy: Always
        env:
        - name: "DATA_ROOT"
          value: "/project2"
        - name: DATASET_VERSION
          valueFrom:
            configMapKeyRef:
              name: playlists-config
              key: DATASET_VERSION
        - name: DATASET_URL
          valueFrom:
            configMapKeyRef:
              name: playlists-config
              key: DATASET_URL
        volumeMounts:
        - mountPath: /project2
          name: project2-pv2-bernardosilva-volume
      volumes:
      - name: project2-pv2-bernardosilva-volume
        persistentVolumeClaim:
          claimName: project2-pv2-bernardosilva