apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-bernardosilva
spec:
  storageClassName: default-storage-class-bernardosilva
  selector:
    matchLabels:
      namespace: bernardosilva
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
